require: rubocop-rake

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  Enabled: false

